"""Create an honest, task-neutral starting tree for one new Corridor."""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path
from typing import Any

from .acceptance import ACCEPTANCE_SCHEMA, validate_acceptance_ledger
from .core import KIT_VERSION, CorridorKitError, atomic_write_bytes, atomic_write_json, sha256_json


SCAFFOLD_SCHEMA = "charting-loop/corridor-kit-scaffold/v1"


def starter_acceptance_ledger() -> dict[str, Any]:
    """Return a structurally honest draft that cannot imply task readiness."""

    return {
        "schema_version": ACCEPTANCE_SCHEMA,
        "coverage": {
            "status": "incomplete",
            "unmapped_clauses": [
                {
                    "source_ref": "public task sources",
                    "statement": "Task clauses have not yet been mapped into atomic acceptance items.",
                    "reason": "This is the uncompiled starter emitted before task inspection.",
                }
            ],
            "ambiguous_clauses": [],
        },
        "construction_readiness": {
            "status": "unresolved",
            "coupled_acceptance_ids": [],
            "replay_entrypoint": "",
            "unresolved_constraints": [
                "Task-specific acceptance, coupled constraints, and replay checks have not yet been compiled."
            ],
        },
        "items": [],
    }


STARTER_README = """# Task-specific Corridor (uncompiled starter)

This directory was initialized from the frozen, task-neutral Corridor kit. It is an
advisory aid, not an answer, an authority source, or a mandatory workflow gate.

Before the Corridor is frozen, the Builder must:

1. Re-read every public task source and replace the starter gap in `ACCEPTANCE.json`
   with atomic acceptance items using exact source references, scope, Rule, and typed
   relations.
2. Record interacting hard requirements in `construction_readiness`, then implement
   one replayable task adapter that evaluates those requirements together.
3. Keep task observations and command output under builder scratch during construction;
   include only reusable task diagnostics, tests, and documentation in this directory.
4. Run strict validation without draft mode. Incomplete or unresolved output is an
   honest diagnostic, not permission to claim success.

After runner-owned freezing, both Worker and QA receive these same bytes and the same
digest. Each role independently checks the public task sources. QA treats Corridor
output as evidence to audit, never as proof of its own completeness.

The generated `task_adapter.py` reports `unresolved` until the Builder replaces its
task-specific functions. It never mutates the target by itself.
"""


STARTER_ADAPTER = '''#!/usr/bin/env python3
"""Task adapter boundary generated by corridor-kit; replace during construction."""

from __future__ import annotations

import argparse
import json


def unresolved(command: str) -> dict[str, object]:
    return {
        "schema_version": "charting-loop/task-adapter-report/v1",
        "status": "unresolved",
        "command": command,
        "reason": "The Builder has not compiled the task-specific adapter.",
        "authorizes_mutation": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Advisory task-specific Corridor adapter")
    parser.add_argument("command", choices=("survey", "check", "guide"))
    args = parser.parse_args()
    print(json.dumps(unresolved(args.command), sort_keys=True))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''


FIXTURES_README = """# Task-specific fixtures

The Builder may add synthetic or public-source-derived fixtures here. Do not copy a
prior benchmark's fixtures, hidden verifier material, candidate answer, or writeback.
"""


EVIDENCE_README = """# Evidence interface

Task diagnostics may emit replay reports here or into runner-owned scratch. Reports
must identify the command, public inputs, result, and acceptance IDs they bear on.
They are evidence for Worker and QA, not self-issued acceptance or authority.
"""


def _write_scaffold_tree(root: Path) -> None:
    (root / "fixtures").mkdir()
    (root / "evidence").mkdir()
    ledger = starter_acceptance_ledger()
    report = validate_acceptance_ledger(ledger, allow_draft=True)
    if not report.ok:
        raise CorridorKitError(f"internal starter ledger is invalid: {report.errors}")
    atomic_write_json(root / "ACCEPTANCE.json", ledger)
    atomic_write_bytes(root / "README.md", STARTER_README.encode("utf-8"))
    atomic_write_bytes(
        root / "task_adapter.py", STARTER_ADAPTER.encode("utf-8"), mode=0o755
    )
    atomic_write_bytes(
        root / "fixtures" / "README.md", FIXTURES_README.encode("utf-8")
    )
    atomic_write_bytes(
        root / "evidence" / "README.md", EVIDENCE_README.encode("utf-8")
    )
    identity_input = {
        "acceptance": ledger,
        "readme": STARTER_README,
        "adapter": STARTER_ADAPTER,
        "fixtures_readme": FIXTURES_README,
        "evidence_readme": EVIDENCE_README,
    }
    atomic_write_json(
        root / "KIT.json",
        {
            "schema_version": SCAFFOLD_SCHEMA,
            "kit_version": KIT_VERSION,
            "state": "uncompiled",
            "task_specific": False,
            "authorizes_mutation": False,
            "worker_and_qa_shared_after_freeze": True,
            "starter_digest": sha256_json(identity_input),
            "generated_files": [
                "ACCEPTANCE.json",
                "README.md",
                "task_adapter.py",
                "fixtures/README.md",
                "evidence/README.md",
            ],
        },
    )


def create_scaffold(output: Path) -> Path:
    """Atomically install a new scaffold without replacing existing task data."""

    output = Path(output)
    if output.exists() or output.is_symlink():
        raise CorridorKitError(f"scaffold output already exists: {output}")
    parent = output.parent
    parent.mkdir(parents=True, exist_ok=True)
    if parent.is_symlink() or not parent.is_dir():
        raise CorridorKitError(f"scaffold parent must be a real directory: {parent}")
    staging = Path(tempfile.mkdtemp(prefix=f".{output.name}.", dir=parent))
    try:
        _write_scaffold_tree(staging)
        os.replace(staging, output)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return output
